name: "Festa F310GP Monitor"
description: "Festa F310GP MQTT Auto-Discovery via SSH"
version: "1.0.4"
slug: "f310gp"
init: false
arch:
  - aarch64
  - amd64
host_network: true
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  mqtt_prefix: "homeassistant"
  switch_hosts: ""
  switch_users: ""
  switch_passwords: ""
  poll_interval: 60
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str?
  mqtt_password: password?
  mqtt_prefix: str?
  switch_hosts: str
  switch_users: str
  switch_passwords: password
  poll_interval: int
